### ISSUE TITLE
Add support for <type>Var methods

### ISSUE THREAD

**Issue by daniellowtw** [mwitkow/go-flagz#14]
FlagSets have methods for creating a flag with a pointer to the variable that stores the value. It would be nice to have that feature for consistency.

https://godoc.org/flag#FlagSet.BoolVar

**Comment by mwitkow** [comment]
The whole purpose of `Dyn` flags is that they are not pointers: they have thread-safety built in. 
You can still use standard `*Var` from FlagSet, just not in a dynamic fashion.
